#***REMOVED***Spring***REMOVED***Boot***REMOVED***应用配置
server:
***REMOVED******REMOVED***port:***REMOVED***9092

spring:
***REMOVED******REMOVED***application:
***REMOVED******REMOVED******REMOVED******REMOVED***name:***REMOVED***mymusic-springboot
***REMOVED******REMOVED***
***REMOVED******REMOVED***#***REMOVED***数据源配置
***REMOVED******REMOVED***datasource:
***REMOVED******REMOVED******REMOVED******REMOVED***driver-class-name:***REMOVED***com.mysql.cj.jdbc.Driver
***REMOVED******REMOVED******REMOVED******REMOVED***url:***REMOVED***jdbc:mysql://localhost:3306/mymusic?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
***REMOVED******REMOVED******REMOVED******REMOVED***username:***REMOVED***root
***REMOVED******REMOVED******REMOVED******REMOVED***password:***REMOVED***admin123

#***REMOVED***MyBatis配置
mybatis:
***REMOVED******REMOVED***#***REMOVED***mapper文件位置
***REMOVED******REMOVED***mapper-locations:***REMOVED***classpath:mapper/*.xml
***REMOVED******REMOVED***#***REMOVED***实体类包路径
***REMOVED******REMOVED***type-aliases-package:***REMOVED***org.example.entity
***REMOVED******REMOVED***configuration:
***REMOVED******REMOVED******REMOVED******REMOVED***#***REMOVED***开启驼峰命名转换
***REMOVED******REMOVED******REMOVED******REMOVED***map-underscore-to-camel-case:***REMOVED***true