#***REMOVED***Spring***REMOVED***Boot***REMOVED***应用配置
server:
***REMOVED******REMOVED***port:***REMOVED***9092

spring:
***REMOVED******REMOVED***application:
***REMOVED******REMOVED******REMOVED******REMOVED***name:***REMOVED***mymusic-springboot
***REMOVED******REMOVED***
***REMOVED******REMOVED***#***REMOVED***数据源配置
***REMOVED******REMOVED***datasource:
***REMOVED******REMOVED******REMOVED******REMOVED***driver-class-name:***REMOVED***com.mysql.cj.jdbc.Driver
***REMOVED******REMOVED******REMOVED******REMOVED***url:***REMOVED***jdbc:mysql://localhost:3306/mymusic?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
***REMOVED******REMOVED******REMOVED******REMOVED***username:***REMOVED***root
***REMOVED******REMOVED******REMOVED******REMOVED***password:***REMOVED***admin123

#***REMOVED***MyBatis配置
mybatis:
***REMOVED******REMOVED***#***REMOVED***mapper文件位置
***REMOVED******REMOVED***mapper-locations:***REMOVED***classpath:mapper/*.xml
***REMOVED******REMOVED***#***REMOVED***实体类包路径
***REMOVED******REMOVED***type-aliases-package:***REMOVED***org.example.entity
***REMOVED******REMOVED***configuration:
***REMOVED******REMOVED******REMOVED******REMOVED***#***REMOVED***开启驼峰命名转换
***REMOVED******REMOVED******REMOVED******REMOVED***map-underscore-to-camel-case:***REMOVED***true

#***REMOVED***阿里云***REMOVED***OSS***REMOVED***配置（请改为你的实际信息，建议使用环境变量覆盖）
oss:
***REMOVED******REMOVED***bucket:***REMOVED***my-music-avatar
***REMOVED******REMOVED***region:***REMOVED***oss-cn-beijing
***REMOVED******REMOVED***endpoint:***REMOVED***https://oss-cn-beijing.aliyuncs.com
***REMOVED******REMOVED***#***REMOVED***仅服务器端持有永久***REMOVED***AK/SK；请不要提交真实值到仓库
***REMOVED******REMOVED***accessKeyId:***REMOVED***LTAI5tHnpGBUrEQN3qPh62m7
***REMOVED******REMOVED***accessKeySecret:***REMOVED***TMwR4nlxT2vWXOO36WedqtdlOVs5Qs
***REMOVED******REMOVED***#***REMOVED***头像文件前缀
***REMOVED******REMOVED***avatarPrefix:***REMOVED***avatars/
***REMOVED******REMOVED***#***REMOVED***直传回调可选：若需要***REMOVED***OSS***REMOVED***回调到你服务器，请再补充***REMOVED***callback